version: 1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2013
configuration: Release
install:
- cmd: >-
    if not exist build mkdir build

    cd build

    cmake -G "Visual Studio 12" -T v120_xp ..
build_script:
- cmd: cmake --build . --target ALL_BUILD --config Release

