language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsdl2-dev
      - libjpeg-turbo8-dev
      - zlib1g-dev
      - libpng12-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zlib libjpeg libpng sdl2 --universal; fi

script:
  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2


#dist: trusty

#install:
#  - ./tools/travis-install.sh "${host:-native}" "${flavour:-Release}" $opts

#script:
#  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

#compiler: gcc
#env:
#  - ""
#  - flavour=Debug
#  - host=i686-linux-gnu
#  - host=i686-w64-mingw32
#  - host=x86_64-w64-mingw32

# One extra build with clang, its warnings are often better
#matrix:
#  include:
#    - compiler: clang
#      env: ""
