language: cpp

addons:
  apt:
    packages:
      - libsdl2-dev
      - libjpeg-turbo8-dev
      - zlib1g-dev
      - libpng12-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 --universal; fi

script:
  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode7.2
      compiler: clang

before_deploy:
  - export DEPLOY_FILE_NAME=jkgalaxies_$TRAVIS_OS_NAME.zip
  - echo "zipping directory"
  - cd ./prefix/JediAcademy
  - zip -r $DEPLOY_FILE_NAME 1/
  - cd ../..
  - echo "deploying $DEPLOY_FILE_NAME to GitHub"

deploy:
  provider: releases
  api_key: " 8fae8c3136da607ced3991b0f1bf76a4524eb5fc"
  file_glob: true
  file: "./prefix/JediAcademy/$DEPLOY_FILE_NAME"
  skip_cleanup: true
  on:
    tags: true


#dist: trusty

#install:
#  - ./tools/travis-install.sh "${host:-native}" "${flavour:-Release}" $opts

#script:
#  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

#compiler: gcc
#env:
#  - ""
#  - flavour=Debug
#  - host=i686-linux-gnu
#  - host=i686-w64-mingw32
#  - host=x86_64-w64-mingw32

# One extra build with clang, its warnings are often better
#matrix:
#  include:
#    - compiler: clang
#      env: ""
